### ISSUE TITLE
Tutorial COMPOSE returns None

### ISSUE THREAD

**Issue by smythp** [niklasb/dryscrape#31]
Looks to be a great tool, and apologies if I'm missing something obvious. Running the second example in the docs (the Gmail one) and getting a None object back from the sess.at_xpath('//*[contains(text(), "COMPOSE")]') search. I've had a look at the source and there is definitely text corresponding with COMPOSE. Also entered a direct xpath to the button, which also turned up None. Any thoughts?

**Comment by niklasb** [comment]
Hi @smythp, I just tried the example and while it failed to send the message, it *did* find the Compose button. Initially however it wanted me to verify my phone number, so that obviously interferred. The XPath works though after I manage to properly load the page.
I will try to fix the example.

As for your problem, seeing as I can't really reproduce it, could you check for me whether XPath generally works? Is it just this specific DOM element that you can't seem to query? Can you try loading the DOM explicitly using lxml.etree.parse(sess.body(), lxml.etree.HTMLParser()) and try to execute the XPath on the resulting document tree? Does it work there?

**Comment by smythp** [comment]
OK, played around with it a bit, still can't get the message to send but got this error instead: 

webkit_server.InvalidResponseError: {"class":"ClickFailed","message":"Failed to find position for element /html/body/script[3] because it is not visible"}

Is this a webkit bug? The xpath function seems to be working for me, I tested it with some code to find all the anchor tags on the page. Didn't have much luck with lxml, though usually use BeautifulSoup myself and may be doing something wrong.

**Comment by niklasb** [comment]
Seems like the element you selected is a Javascript, which makes sense, it probably contains the text as well inside the code. You should probably use a more specific selector, I will update the example accordingly.

**Comment by smythp** [comment]
Appreciate it!

**Comment by niklasb** [comment]
I decided to remove the example, it would have broken anyway the next time they changed their markup.

**Comment by smythp** [comment]
Fair enough. Wound up using Selenium as my job was quick and dirty, but will check back in next time I'm doing some scraping.
