### ISSUE TITLE
Login to facebook, cookies not enabled 

### ISSUE THREAD

**Issue by Metonimie** [niklasb/dryscrape#51]
I'm trying to use dryscrape to login to facebook and I'm getting "Cookies Required" (Cookies are not enabled on your browser, please enable them). How can I avoid this?
Here's my code:
```python
    sess = dryscrape.Session(base_url="https://www.facebook.com/")
    sess.visit("/login")
    f = sess.at_xpath('//*[@name="email"]')
    f.set("...")
    f = sess.at_xpath('//*[@name="pass"]')
    f.set("...")
    f.form().submit()
    # sess.visit("/")
    sess.render("test.png")
```

**Comment by niklasb** [comment]
Not sure. dryscrape definitely supports cookies and your code works for me to log into my personal Facebook account. Maybe they are filtering you based on something else, like a filter to detect repeated automated scrapes? In any case, I am inclined to close this issue for now since I cannot reproduce it.

**Comment by Metonimie** [comment]
That's weird. Thank you!

**Comment by JulienSoda** [comment]
Hello I have the same problem.
My code works on my deskstop and one server. But in another server (nearly same configuration), it doesn't works. Facebook returns: you're browser doesnt accept cookie.
Is there a way to force cookies with dryscrape or qt webkit ? 
Maybe jar library, or directory to create ? 
Any Idea ?

Thanks
Best Regards
